version: 0.2
env:
  variables:
    TEST_ENV_VARIABLE: DEMOAPP
phases:
  install:
    runtime-versions:
      dotnet: 6.0.x
  pre_build:
    commands:
      - echo Restore started at `date`
      - dotnet restore DemoAPI/DemoAPI.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output DemoAPI/DemoAPI.csproj
artifacts:
  files:
    - DemoAPI/build_output/**/*
  base-directory: ./bin/Release/net6.0/publish/
  name: $Env:TEST_ENV_VARIABLE-$(Get-Date -UFormat "%Y%m%d-%H%M%S")
  discard-paths: no