version: 0.2
# env:
#   variables:
#     TEST_ENV_VARIABLE: DEMOAPP
phases:
  # install:
  #   runtime-versions:
  #     dotnet: 5.0
  pre_build:
    commands:
      - echo Restore started at `date`
      - dotnet restore DemoAPI/DemoAPI.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release DemoAPI/DemoAPI.csproj
      - 'dir ./DemoAPI/bin/release/net5.0/publish'
  post_build:
    commands:
      - echo dir
      #- zip -r build.zip DemoAPI/bin/release/net5.0/publish/**/*
artifacts:
  discard-paths: yes
  files:
    - build.zip
