version: 0.2
env:
  variables:
    TEST_ENV_VARIABLE: DEMOAPP
phases:
  install:
    runtime-versions:
      dotnet: 5.0
  pre_build:
    commands:
      - echo Restore started at `date`
      - dotnet restore DemoAPI/DemoAPI.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build-output DemoAPI/DemoAPI.csproj
      - 'dir ./build-output'
artifacts:
  files:
    - 'DemoAPI/build_output/**/*'