version: 0.0
env:
  variables:
    TEST_ENV_VARIABLE: DEMOAPP
phases:
  pre_build:
    commands:
      - echo Restore started at `date`
      - dotnet restore DemoAPI/DemoAPI.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output DemoAPI/DemoAPI.csproj
  artifacts:
    files:
      - DemoAPI/build_output/**/*